[rust]
dependencies = []
content  = []
makefile = "makefiles/rust.makefile"
version = "installer"

[homebrew]
dependencies = []
content  = []
makefile = "makefiles/homebrew.makefile"
version = "installer"

[arduino-cli]
dependencies = []
content  = ["http://downloads.arduino.cc/arduino-cli/arduino-cli-0.2.2-alpha.preview-linux64.tar.bz2", "http://downloads.arduino.cc/arduino-cli/arduino-cli-0.2.2-alpha.preview-linux32.tar.bz2", "http://downloads.arduino.cc/arduino-cli/arduino-cli-0.2.2-alpha.preview-linuxarm.tar.bz2", "http://downloads.arduino.cc/arduino-cli/arduino-cli-0.2.2-alpha.preview-windows.zip", "http://downloads.arduino.cc/arduino-cli/arduino-cli-0.2.2-alpha.preview-osx.zip"]
makefile = "makefiles/arduino-cli.makefile"
version = "v0.2.2-alpha"

[bat]
dependencies = ["rust"]
content = ["https://github.com/sharkdp/bat/archive/v0.7.0.tar.gz"]
makefile = "makefiles/bat.makefile"
version = "v0.7.0"

[pinst]
dependencies = ["rust"]
content = []
makefile = "makefiles/pinst.makefile"
version = "v0.3.0-alpha"
